# Predicting heavy-equipment resale value

## Project goal

This notebook develops an interpretable model of **auction sale price** using historical heavy-equipment data from Kaggle's *Blue Book for Bulldozers* competition. The practical goal is to estimate an asset's residual value from its equipment class, age, meter hours, and sale year. That estimate can later serve as one input to a rent-versus-own or replacement calculator.

## Modeling approach

The analysis is intentionally iterative. It begins with a simple ordinary least squares (OLS) baseline, diagnoses weaknesses in the raw data, and adds complexity only when the results show that it is useful.

1. Load and narrow the source data.
2. Create age and market-year features.
3. Establish a simple price baseline.
4. Test log transformations and nonlinear age effects.
5. Investigate missing, zero, and physically impossible meter readings.
6. Replace broad product groups with detailed equipment classes.
7. Validate on the latest year rather than a random sample.
8. Measure reliability by equipment class and export the production artifacts.

> **Scope:** This is a residual-value model, not a repair-cost or maintenance-cost model. It estimates likely auction price from historical sales. The final estimate should be combined with operating, repair, financing, and rental costs before making an equipment decision.

## 1. Record the software environment

Model files can behave differently across library versions, especially when they are serialized for use in another application. Printing the Python and package versions creates a lightweight reproducibility record and makes deployment problems easier to diagnose later.

In [ ]:
import sys
import sklearn
import statsmodels
import joblib
import pandas
import numpy

print("Python:", sys.version)
print("scikit-learn:", sklearn.__version__)
print("statsmodels:", statsmodels.__version__)
print("joblib:", joblib.__version__)
print("pandas:", pandas.__version__)
print("numpy:", numpy.__version__)

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
scikit-learn: 1.6.1
statsmodels: 0.15.0
joblib: 1.6.0
pandas: 2.2.3
numpy: 2.1.3

## 2. Load the auction data

The source file contains historical auction records for many types of heavy equipment. `saledate` is parsed as a date at import so calendar-year features can be calculated reliably. `low_memory=False` asks pandas to inspect complete columns before deciding their data types, which avoids mixed-type warnings on this wide file.

The preview is a quick structural check: it confirms that the download succeeded and that the expected fields are present before further work begins.

In [ ]:
import pandas as pd

url = "https://xplainable-public-storage.syd1.digitaloceanspaces.com/example_data/TrainAndValid.csv"

df = pd.read_csv(
    url,
    parse_dates=["saledate"],
    low_memory=False
)

df.head()

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000.0,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000.0,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000.0,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500.0,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000.0,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Select the first modeling fields and engineer age

The initial table keeps only the target and a small set of intuitive predictors:

- **SalePrice:** the auction price to predict.
- **YearMade:** the machine's manufacturing year.
- **MachineHoursCurrentMeter:** cumulative recorded operating hours.
- **ProductGroup / ProductGroupDesc:** broad equipment type.
- **saledate:** the timing of the auction.

Two features are derived from the sale date. `sale_year` represents market conditions at the time of sale, while `equipment_age` represents physical age. Keeping those concepts separate matters: two identical ten-year-old machines may sell for different amounts in different market years.

In [ ]:
cols = [
    "SalePrice",
    "YearMade",
    "MachineHoursCurrentMeter",
    "saledate",
    "ProductGroup",
    "ProductGroupDesc"
]

equipment = df[cols].copy()

equipment["sale_year"] = equipment["saledate"].dt.year
equipment["equipment_age"] = (
    equipment["sale_year"] - equipment["YearMade"]
)

## 4. Define the initial modeling population

The first pass retains rows where meter hours are present. A regression cannot use a missing numeric predictor without an imputation strategy, and imputation would introduce an additional assumption before the quality of the meter field has been understood.

At this point, a recorded value of zero is still treated as observed data. The next diagnostics determine whether that is reasonable.

In [ ]:
model_df = equipment[
    equipment["MachineHoursCurrentMeter"].notna()
].copy()

## 5. Remove impossible manufacturing dates

Records are limited to equipment made in 1950 or later and to nonnegative calculated ages. These rules remove obvious coding problems such as placeholder manufacture years and machines that appear to have been sold before they were built.

This is a conservative cleaning step: it removes logically invalid rows without trimming legitimate old equipment simply because it is unusual.

In [ ]:
model_df = model_df[
    (model_df["YearMade"] >= 1950) &
    (model_df["equipment_age"] >= 0)
].copy()

### Initial distribution check

Descriptive statistics reveal the scale and shape of the three main numeric fields. The results show approximately **130,000 usable records**, a median sale price near **$27,000**, and a median equipment age of **7 years**. Meter hours are much more problematic: the median is only 399, the 25th percentile is zero, and the maximum exceeds 2.4 million hours.

Those meter results are the first indication that zeros may represent unknown values and that some positive readings may also be invalid. They motivate the more detailed quality checks later in the notebook.

In [ ]:
model_df[
    [
        "SalePrice",
        "equipment_age",
        "MachineHoursCurrentMeter"
    ]
].describe()

           SalePrice  equipment_age  MachineHoursCurrentMeter
count  130521.000000  130521.000000              1.305210e+05
mean    34824.763909       9.899005              3.408614e+03
std     24961.143493       7.670566              2.662534e+04
min      4750.000000       0.000000              0.000000e+00
25%     16000.000000       5.000000              0.000000e+00
50%     27000.000000       7.000000              3.990000e+02
75%     46000.000000      13.000000              3.266000e+03
max    142000.000000      60.000000              2.483300e+06

## 6. Establish a deliberately simple baseline

The first OLS model predicts sale price directly from age and raw meter hours. Its purpose is not to be the final model; it provides a benchmark for judging whether later features genuinely improve explanatory power.

The low R² (about **0.05**) shows that age and raw meter hours alone explain very little of the price variation. The positive hours coefficient is also counterintuitive. That does not necessarily mean additional use increases value—it is a warning that equipment size/type and poor meter data are confounding the relationship.

In [ ]:
import statsmodels.formula.api as smf

model = smf.ols(
    """
    SalePrice ~
    equipment_age +
    MachineHoursCurrentMeter
    """,
    data=model_df
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.048
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     3311.
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:01   Log-Likelihood:            -1.5035e+06
No. Observations:              130521   AIC:                         3.007e+06
Df Residuals:                  130518   BIC:                         3.007e+06
Df Model:                           2
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                 4.183e+04    110.341    379.079      0.000    4.16e+04     4.2e+04
equipment_age             -713.1261      8.787    -81.153      0.000    -730.349    -695.903
MachineHoursCurrentMeter     0.0164      0.003      6.481      0.000       0.011       0.021
==============================================================================
Omnibus:                    24191.622   Durbin-Watson:                   0.629
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            41329.344
Skew:                           1.227   Prob(JB):                         0.00
Kurtosis:                       4.254   Cond. No.                     4.40e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.4e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

## 7. Control for broad equipment type

Equipment types operate on very different price scales, so `C(ProductGroup)` adds a separate categorical adjustment for each broad group. This prevents the model from treating a skid steer and a motor grader as directly comparable simply because their ages and hours are similar.

R² rises from roughly **0.05 to 0.40**, demonstrating that equipment identity is far more important than age or hours alone. The large improvement also suggests that an even more detailed class variable may be valuable later.

In [ ]:
model_type = smf.ols(
    """
    SalePrice ~
    equipment_age +
    MachineHoursCurrentMeter +
    C(ProductGroup)
    """,
    data=model_df
).fit()

print(model_type.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.402
Model:                            OLS   Adj. R-squared:                  0.402
Method:                 Least Squares   F-statistic:                 1.253e+04
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:02   Log-Likelihood:            -1.4732e+06
No. Observations:              130521   AIC:                         2.946e+06
Df Residuals:                  130513   BIC:                         2.946e+06
Df Model:                           7
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                 3.462e+04    138.554    249.891      0.000    3.44e+04    3.49e+04
C(ProductGroup)[T.MG]     5.115e+04    268.603    190.416      0.000    5.06e+04    5.17e+04
C(ProductGroup)[T.SSL]   -1.474e+04    195.934    -75.247      0.000   -1.51e+04   -1.44e+04
C(ProductGroup)[T.TEX]    1.685e+04    161.574    104.299      0.000    1.65e+04    1.72e+04
C(ProductGroup)[T.TTT]    2.122e+04    172.413    123.102      0.000    2.09e+04    2.16e+04
C(ProductGroup)[T.WL]     2.419e+04    179.368    134.852      0.000    2.38e+04    2.45e+04
equipment_age            -1372.0225      7.520   -182.456      0.000   -1386.761   -1357.284
MachineHoursCurrentMeter     0.0073      0.002      3.654      0.000       0.003       0.011
==============================================================================
Omnibus:                    16347.001   Durbin-Watson:                   0.788
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28741.863
Skew:                           0.841   Prob(JB):                         0.00
Kurtosis:                       4.567   Cond. No.                     1.69e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.69e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

## 8. Model proportional rather than absolute price differences

Auction prices are right-skewed, and a $10,000 error has a very different meaning for a $15,000 machine than for a $150,000 machine. Applying `log1p` to sale price:

- reduces the influence of the highest-priced equipment,
- makes the residual spread more consistent across price levels, and
- lets effects be interpreted approximately as percentage changes rather than fixed dollar changes.

The log-price model reaches an R² of about **0.49**, an improvement over modeling raw dollars with the same predictors. Predictions will later be converted back to dollars with `expm1`.

In [ ]:
import numpy as np

model_df["log_sale_price"] = np.log1p(
    model_df["SalePrice"]
)

log_model = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    MachineHoursCurrentMeter +
    C(ProductGroup)
    """,
    data=model_df
).fit()

print(log_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.491
Model:                            OLS   Adj. R-squared:                  0.491
Method:                 Least Squares   F-statistic:                 1.796e+04
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:02   Log-Likelihood:                -95586.
No. Observations:              130521   AIC:                         1.912e+05
Df Residuals:                  130513   BIC:                         1.913e+05
Df Model:                           7
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                   10.3203      0.004   2857.122      0.000      10.313      10.327
C(ProductGroup)[T.MG]        1.2073      0.007    172.410      0.000       1.194       1.221
C(ProductGroup)[T.SSL]      -0.7814      0.005   -152.980      0.000      -0.791      -0.771
C(ProductGroup)[T.TEX]       0.3940      0.004     93.534      0.000       0.386       0.402
C(ProductGroup)[T.TTT]       0.5525      0.004    122.925      0.000       0.544       0.561
C(ProductGroup)[T.WL]        0.6417      0.005    137.221      0.000       0.633       0.651
equipment_age               -0.0402      0.000   -205.033      0.000      -0.041      -0.040
MachineHoursCurrentMeter  1.727e-07   5.23e-08      3.298      0.001    7.01e-08    2.75e-07
==============================================================================
Omnibus:                     3337.588   Durbin-Watson:                   0.754
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3727.332
Skew:                          -0.371   Prob(JB):                         0.00
Kurtosis:                       3.367   Cond. No.                     1.69e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.69e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

### Rescale meter hours for readability

Dividing operating hours by 1,000 changes only the units, not the information or model fit. A coefficient on `machine_hours_1000` describes the effect of an additional 1,000 hours, which is easier to read than a coefficient for one hour. The following refit confirms that rescaling does not alter the model's explanatory power.

In [ ]:
model_df["machine_hours_1000"] = (
    model_df["MachineHoursCurrentMeter"] / 1000
)

In [ ]:
log_model = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    machine_hours_1000 +
    C(ProductGroup)
    """,
    data=model_df
).fit()

print(log_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.491
Model:                            OLS   Adj. R-squared:                  0.491
Method:                 Least Squares   F-statistic:                 1.796e+04
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:03   Log-Likelihood:                -95586.
No. Observations:              130521   AIC:                         1.912e+05
Df Residuals:                  130513   BIC:                         1.913e+05
Df Model:                           7
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 10.3203      0.004   2857.122      0.000      10.313      10.327
C(ProductGroup)[T.MG]      1.2073      0.007    172.410      0.000       1.194       1.221
C(ProductGroup)[T.SSL]    -0.7814      0.005   -152.980      0.000      -0.791      -0.771
C(ProductGroup)[T.TEX]     0.3940      0.004     93.534      0.000       0.386       0.402
C(ProductGroup)[T.TTT]     0.5525      0.004    122.925      0.000       0.544       0.561
C(ProductGroup)[T.WL]      0.6417      0.005    137.221      0.000       0.633       0.651
equipment_age             -0.0402      0.000   -205.033      0.000      -0.041      -0.040
machine_hours_1000         0.0002   5.23e-05      3.298      0.001    7.01e-05       0.000
==============================================================================
Omnibus:                     3337.588   Durbin-Watson:                   0.754
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3727.332
Skew:                          -0.371   Prob(JB):                         0.00
Kurtosis:                       3.367   Cond. No.                         170.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 9. Diagnose the meter-hours field

Before relying on meter hours, the notebook examines its percentiles, the share of exact zeros, group-level distributions, and correlations. Nearly **48% of the initial records have a zero meter reading**, making it unlikely that every zero represents a genuinely unused machine.

The working interpretation is that many zeros are missing or unavailable readings encoded as `0`. Because that issue can obscure the true relationship between use and resale value, the analysis compares models with and without those rows rather than silently accepting them.

In [ ]:
model_df["MachineHoursCurrentMeter"].describe(
    percentiles=[.01, .05, .25, .5, .75, .95, .99]
)

count    1.305210e+05
mean     3.408614e+03
std      2.662534e+04
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      3.990000e+02
75%      3.266000e+03
95%      1.031300e+04
99%      2.067140e+04
max      2.483300e+06
Name: MachineHoursCurrentMeter, dtype: float64

In [ ]:
(model_df["MachineHoursCurrentMeter"] == 0).mean()

np.float64(0.4769883773492388)

In [ ]:
model_df.groupby("ProductGroup")[
    "MachineHoursCurrentMeter"
].describe()

,count,mean,std,min,25%,50%,75%,max
ProductGroup,,,,,,,,
BL,24916.0,2532.767860,21362.593040,0.0,0.0,8.0,2580.00,932000.0
MG,7177.0,2864.812596,19741.876651,0.0,0.0,0.0,3073.00,1194900.0
SSL,16142.0,2288.886012,29255.292989,0.0,0.0,888.5,1833.00,2483300.0
TEX,33546.0,4171.807160,29781.180624,0.0,0.0,1297.0,4555.75,2202400.0
TTT,26194.0,3295.567916,26109.451676,0.0,0.0,0.0,3240.00,1711700.0
WL,22546.0,4347.099086,27343.659002,0.0,0.0,0.0,4945.00,1728600.0

In [ ]:
model_df[
    ["equipment_age", "MachineHoursCurrentMeter", "log_sale_price"]
].corr()

,equipment_age,MachineHoursCurrentMeter,log_sale_price
equipment_age,1.000000,0.006149,-0.222297
MachineHoursCurrentMeter,0.006149,1.000000,0.016660
log_sale_price,-0.222297,0.016660,1.000000

## 10. Allow depreciation to curve with age

Straight-line depreciation assumes each additional year changes log price by the same amount. In practice, equipment often loses value quickly when newer and more slowly once it is older. Adding `age_squared` allows one smooth curve to represent that changing rate.

Adjusted R² increases only modestly—from about **0.491 to 0.496**—but the comparison shows that the nonlinear term contains useful information. Both age terms must be interpreted together; the positive squared term does not mean old equipment appreciates on its own.

In [ ]:
model_df["age_squared"] = model_df["equipment_age"] ** 2

model_age_curve = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    machine_hours_1000 +
    C(ProductGroup)
    """,
    data=model_df
).fit()

print(model_age_curve.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.496
Model:                            OLS   Adj. R-squared:                  0.496
Method:                 Least Squares   F-statistic:                 1.607e+04
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:03   Log-Likelihood:                -94869.
No. Observations:              130521   AIC:                         1.898e+05
Df Residuals:                  130512   BIC:                         1.898e+05
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 10.4300      0.005   2262.589      0.000      10.421      10.439
C(ProductGroup)[T.MG]      1.1872      0.007    169.976      0.000       1.173       1.201
C(ProductGroup)[T.SSL]    -0.8015      0.005   -156.930      0.000      -0.812      -0.792
C(ProductGroup)[T.TEX]     0.3871      0.004     92.324      0.000       0.379       0.395
C(ProductGroup)[T.TTT]     0.5405      0.004    120.619      0.000       0.532       0.549
C(ProductGroup)[T.WL]      0.6363      0.005    136.762      0.000       0.627       0.645
equipment_age             -0.0596      0.001   -109.037      0.000      -0.061      -0.059
age_squared                0.0006   1.52e-05     37.971      0.000       0.001       0.001
machine_hours_1000         0.0002   5.21e-05      4.656      0.000       0.000       0.000
==============================================================================
Omnibus:                     3694.415   Durbin-Watson:                   0.752
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4267.231
Skew:                          -0.380   Prob(JB):                         0.00
Kurtosis:                       3.455   Cond. No.                     2.03e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.03e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
print("Linear age:", log_model.rsquared_adj)
print("Curved age:", model_age_curve.rsquared_adj)

Linear age: 0.4905933077741783
Curved age: 0.49615536625879686

## 11. Isolate machines with reported use

Rows with meter hours greater than zero are placed in a separate dataset. This reduces the sample from about **130,500 to 68,300 records**, but it avoids interpreting likely missing-value placeholders as truly unused equipment.

The adjusted R² changes only slightly at this stage. The value of this filter is therefore mainly data validity and coefficient interpretability, not an immediate jump in fit.

In [ ]:
hours_df = model_df[
    model_df["MachineHoursCurrentMeter"] > 0
].copy()

hours_df["machine_hours_1000"] = (
    hours_df["MachineHoursCurrentMeter"] / 1000
)

hours_df["age_squared"] = (
    hours_df["equipment_age"] ** 2
)

In [ ]:
hours_model = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    machine_hours_1000 +
    C(ProductGroup)
    """,
    data=hours_df
).fit()

print(hours_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.499
Model:                            OLS   Adj. R-squared:                  0.499
Method:                 Least Squares   F-statistic:                     8484.
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:04   Log-Likelihood:                -51232.
No. Observations:               68264   AIC:                         1.025e+05
Df Residuals:                   68255   BIC:                         1.026e+05
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 10.4460      0.007   1562.738      0.000      10.433      10.459
C(ProductGroup)[T.MG]      1.1865      0.012    101.833      0.000       1.164       1.209
C(ProductGroup)[T.SSL]    -0.7805      0.007   -115.251      0.000      -0.794      -0.767
C(ProductGroup)[T.TEX]     0.4092      0.006     69.770      0.000       0.398       0.421
C(ProductGroup)[T.TTT]     0.5424      0.007     83.139      0.000       0.530       0.555
C(ProductGroup)[T.WL]      0.5971      0.007     86.927      0.000       0.584       0.611
equipment_age             -0.0656      0.001    -69.443      0.000      -0.067      -0.064
age_squared                0.0009   3.28e-05     26.811      0.000       0.001       0.001
machine_hours_1000         0.0003   5.39e-05      4.720      0.000       0.000       0.000
==============================================================================
Omnibus:                     3318.435   Durbin-Watson:                   0.891
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3903.268
Skew:                          -0.540   Prob(JB):                         0.00
Kurtosis:                       3.453   Cond. No.                     1.32e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.32e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
print("Original n:", len(model_df))
print("Known-hours n:", len(hours_df))
print("Original adj R²:", model_age_curve.rsquared_adj)
print("Known-hours adj R²:", hours_model.rsquared_adj)

Original n: 130521
Known-hours n: 68264
Original adj R²: 0.49615536625879686
Known-hours adj R²: 0.49852920755374375

In [ ]:
hours_df["MachineHoursCurrentMeter"].describe(
    percentiles=[.01, .05, .25, .50, .75, .95, .99]
)

count    6.826400e+04
mean     6.517281e+03
std      3.654018e+04
min      1.000000e+00
1%       5.863000e+01
5%       4.430000e+02
25%      1.553000e+03
50%      3.067000e+03
75%      6.080250e+03
95%      1.371970e+04
99%      2.926270e+04
max      2.483300e+06
Name: MachineHoursCurrentMeter, dtype: float64

## 12. Apply a physical plausibility check

A machine cannot accumulate more than 8,760 operating hours per year—the number of calendar hours in a year. `max_possible_hours` uses `(age + 1)` so equipment sold during its manufacture year can still have up to one year of use.

Only **380 records** violate this generous upper bound. They are inspected before removal so the rule is transparent and so valid high-use equipment is not confused with impossible readings.

In [ ]:
hours_df["max_possible_hours"] = (
    (hours_df["equipment_age"] + 1) * 8760
)

hours_df["invalid_hours"] = (
    hours_df["MachineHoursCurrentMeter"]
    > hours_df["max_possible_hours"]
)

In [ ]:
hours_df["invalid_hours"].value_counts()

invalid_hours
False    67884
True       380
Name: count, dtype: int64

In [ ]:
hours_df.loc[
    hours_df["invalid_hours"],
    [
        "equipment_age",
        "MachineHoursCurrentMeter",
        "ProductGroup",
        "SalePrice"
    ]
].sort_values(
    "MachineHoursCurrentMeter",
    ascending=False
).head(30)

        equipment_age  MachineHoursCurrentMeter ProductGroup  SalePrice
324615              4                 2483300.0          SSL     8500.0
347409             13                 2202400.0          TEX    12000.0
324899              4                 1857100.0          SSL    12000.0
297550             14                 1729600.0          TEX    22000.0
309643             17                 1728600.0           WL    27000.0
309549             11                 1711700.0          TTT    80000.0
327710              7                 1602900.0           WL    37500.0
301601             14                 1485900.0          TTT    70000.0
305333             10                 1282700.0          TEX    40000.0
348423             15                 1228200.0          TEX    18500.0
328327              8                 1209500.0          TEX    22000.0
328336              8                 1203000.0          TEX    17000.0
325012             15                 1194900.0           MG    38500.0
330979             15                 1189500.0           WL    19000.0
328328              8                 1148500.0          TEX    31000.0
316585              5                 1112100.0           WL    80000.0
294077             11                 1098000.0           WL    32250.0
314500              7                  991000.0          TTT    52500.0
329260              6                  974400.0          TEX    53000.0
354140              7                  968400.0          TEX    34000.0
311404             14                  945300.0          TTT    24000.0
350926             16                  934400.0          TEX    15000.0
301699             12                  932000.0           BL    21000.0
301701             12                  906100.0           BL    17000.0
351153             15                  892700.0           WL    18000.0
304835             10                  886200.0          TTT    23000.0
311796             14                  861300.0           BL    17000.0
369579             14                  821747.0           BL    16500.0
305708              9                  808800.0          TTT    21000.0
340907              7                  792000.0          TTT    21000.0

### Create the cleaned known-hours sample

The impossible readings are removed, leaving **67,884 observations** with positive and physically possible meter hours. The percentile table that follows is another reasonableness check on the cleaned range; it is not an additional trimming rule.

In [ ]:
clean_hours_df = hours_df[
    ~hours_df["invalid_hours"]
].copy()

In [ ]:
clean_hours_df[
    "MachineHoursCurrentMeter"
].describe(
    percentiles=[.01, .05, .25, .5, .75, .95, .99, .995]
)

count     67884.000000
mean       4549.371089
std        4870.526094
min           1.000000
1%           57.000000
5%          439.000000
25%        1547.000000
50%        3043.000000
75%        6010.000000
95%       13147.850000
99%       22652.510000
99.5%     28230.685000
max      161800.000000
Name: MachineHoursCurrentMeter, dtype: float64

## 13. Test a log transformation of operating hours

Meter readings remain strongly right-skewed even after invalid values are removed. `log1p(hours)` compresses the long upper tail and represents diminishing marginal wear: the difference between 500 and 1,500 hours may carry more information than the difference between 20,500 and 21,500 hours.

The raw-hours and log-hours models perform almost identically (adjusted R² about **0.5402 versus 0.5405**). The log version is retained because it is slightly stronger and less sensitive to extreme readings, not because the improvement is dramatic.

In [ ]:
clean_hours_df["log_machine_hours"] = np.log1p(
    clean_hours_df["MachineHoursCurrentMeter"]
)

In [ ]:
model_raw_hours = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    machine_hours_1000 +
    C(ProductGroup)
    """,
    data=clean_hours_df
).fit()

model_log_hours = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    log_machine_hours +
    C(ProductGroup)
    """,
    data=clean_hours_df
).fit()

print("Raw hours:", model_raw_hours.rsquared_adj)
print("Log hours:", model_log_hours.rsquared_adj)

Raw hours: 0.5401665439840656
Log hours: 0.5405348687101796

### Review the most heavily used machines

`hours_per_year` provides context for extreme but still technically possible meter readings. Listing the 20 largest observations is a manual diagnostic: it helps distinguish data errors from machines that plausibly operated for multiple shifts or in high-utilization environments.

No additional rows are removed here. This avoids tailoring the dataset solely to make the regression cleaner.

In [ ]:
clean_hours_df["hours_per_year"] = (
    clean_hours_df["MachineHoursCurrentMeter"]
    / (clean_hours_df["equipment_age"] + 1)
)

clean_hours_df.nlargest(
    20,
    "MachineHoursCurrentMeter"
)[
    [
        "ProductGroup",
        "equipment_age",
        "MachineHoursCurrentMeter",
        "hours_per_year",
        "SalePrice"
    ]
]

,ProductGroup,equipment_age,MachineHoursCurrentMeter,hours_per_year,SalePrice
326954,TTT,30,161800.0,5219.354839,9500.0
349508,TTT,17,120000.0,6666.666667,10250.0
356867,TTT,18,120000.0,6315.789474,8000.0
325707,MG,23,96900.0,4037.500000,13000.0
380741,BL,14,96890.0,6459.333333,21000.0
365299,WL,33,94075.0,2766.911765,16500.0
304842,TEX,14,89300.0,5953.333333,26000.0
380535,TEX,13,78765.0,5626.071429,40000.0
102732,WL,21,78740.0,3579.090909,38000.0
327145,MG,25,76500.0,2942.307692,10000.0
379609,TTT,15,75625.0,4726.562500,52500.0
403284,WL,17,73860.0,4103.333333,75000.0
306696,TTT,13,73800.0,5271.428571,22000.0
381851,TEX,10,70755.0,6432.272727,105000.0
383974,WL,15,69850.0,4365.625000,19000.0
379007,TTT,19,68691.0,3434.550000,54000.0
380890,WL,38,67049.0,1719.205128,19000.0
380716,WL,13,66679.0,4762.785714,37000.0
379323,TTT,20,66678.0,3175.142857,47500.0
380007,WL,20,65362.0,3112.476190,27000.0

### Refit the transformed exploratory model

This model combines the decisions made so far: log sale price, curved age, log meter hours, and broad product group. Its summary is useful for checking coefficient directions, significance, residual diagnostics, and overall fit after cleaning.

The duplicate import and feature statements make this section runnable after the cleaned dataset exists, even if the earlier exploratory cells are rearranged. The following raw-hours refit is retained as a direct sensitivity comparison.

In [ ]:
import numpy as np
import statsmodels.formula.api as smf

clean_hours_df["log_machine_hours"] = np.log1p(
    clean_hours_df["MachineHoursCurrentMeter"]
)

clean_hours_df["age_squared"] = (
    clean_hours_df["equipment_age"] ** 2
)

model_log_hours = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    log_machine_hours +
    C(ProductGroup)
    """,
    data=clean_hours_df
).fit()

print(model_log_hours.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.541
Model:                            OLS   Adj. R-squared:                  0.541
Method:                 Least Squares   F-statistic:                     9984.
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:05   Log-Likelihood:                -47960.
No. Observations:               67884   AIC:                         9.594e+04
Df Residuals:                   67875   BIC:                         9.602e+04
Df Model:                           8
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  9.3715      0.015    626.233      0.000       9.342       9.401
C(ProductGroup)[T.MG]      1.1088      0.011     98.909      0.000       1.087       1.131
C(ProductGroup)[T.SSL]    -0.7227      0.007   -110.509      0.000      -0.736      -0.710
C(ProductGroup)[T.TEX]     0.3419      0.006     60.052      0.000       0.331       0.353
C(ProductGroup)[T.TTT]     0.4912      0.006     78.040      0.000       0.479       0.503
C(ProductGroup)[T.WL]      0.4845      0.007     71.911      0.000       0.471       0.498
equipment_age             -0.1050      0.001   -101.436      0.000      -0.107      -0.103
age_squared                0.0019    3.4e-05     55.963      0.000       0.002       0.002
log_machine_hours          0.1674      0.002     79.314      0.000       0.163       0.172
==============================================================================
Omnibus:                     2203.042   Durbin-Watson:                   1.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2621.660
Skew:                          -0.402   Prob(JB):                         0.00
Kurtosis:                       3.529   Cond. No.                     1.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
model_raw_hours = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    MachineHoursCurrentMeter +
    C(ProductGroup)
    """,
    data=clean_hours_df
).fit()

print("Raw hours:", model_raw_hours.rsquared_adj)
print("Log hours:", model_log_hours.rsquared_adj)

Raw hours: 0.5401665439840656
Log hours: 0.5405348687101796

## 14. Replace broad groups with detailed equipment classes

Broad groups still combine machines with very different capacity and value. `fiProductClassDesc` captures distinctions such as horsepower, operating capacity, digging depth, and tonnage. `ProductSize` is copied for inspection, while the class description becomes the principal categorical predictor.

The fields are joined back by the original dataframe index, preserving alignment with the already-cleaned rows. `sale_year` is also reconstructed from the source date for market adjustment and temporal validation.

In [ ]:
clean_hours_df["fiProductClassDesc"] = (
    df.loc[clean_hours_df.index, "fiProductClassDesc"]
)

In [ ]:
clean_hours_df[
    ["fiProductClassDesc", "ProductSize"]
] = df.loc[
    clean_hours_df.index,
    ["fiProductClassDesc", "ProductSize"]
]

In [ ]:
clean_hours_df["sale_year"] = pd.to_datetime(
    df.loc[clean_hours_df.index, "saledate"]
).dt.year

In [ ]:
clean_hours_df[
    ["fiProductClassDesc", "ProductSize", "sale_year"]
].head()

                                  fiProductClassDesc ProductSize  sale_year
0           Wheel Loader - 110.0 to 120.0 Horsepower         NaN       2006
1           Wheel Loader - 150.0 to 175.0 Horsepower      Medium       2004
2  Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...         NaN       2004
3  Hydraulic Excavator, Track - 12.0 to 14.0 Metr...       Small       2011
4  Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...         NaN       2009

## 15. Compare class detail and market timing

The first detailed model treats sale year as a categorical effect, allowing each auction year to have its own market adjustment. It reaches an adjusted R² of about **0.841**, a major improvement over the broad-group model.

The next fit temporarily excludes year to show how much market timing contributes. The stepwise comparison then adds class, market year, age, and hours in sequence:

- detailed class alone: **0.646** adjusted R²;
- adding market year: **0.658**;
- adding age and curved age: **0.841**;
- adding meter hours: **0.841**.

The key finding is that detailed class and age explain most of the model's performance. Meter hours add relatively little after those fields are known, although they remain operationally meaningful.

In [ ]:
class_year_model = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    log_machine_hours +
    C(fiProductClassDesc) +
    C(sale_year)
    """,
    data=clean_hours_df
).fit()

print(class_year_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.841
Model:                            OLS   Adj. R-squared:                  0.841
Method:                 Least Squares   F-statistic:                     3865.
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:09   Log-Likelihood:                -11877.
No. Observations:               67884   AIC:                         2.394e+04
Df Residuals:                   67790   BIC:                         2.480e+04
Df Model:                          93
Covariance Type:            nonrobust
=======================================================================================================================================================
                                                                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                               9.9972      0.026    379.931      0.000       9.946      10.049
C(fiProductClassDesc)[T.Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth]        0.4617      0.008     54.878      0.000       0.445       0.478
C(fiProductClassDesc)[T.Backhoe Loader - 15.0 to 16.0 Ft Standard Digging Depth]        0.5022      0.011     45.569      0.000       0.481       0.524
C(fiProductClassDesc)[T.Backhoe Loader - 16.0 + Ft Standard Digging Depth]              0.5168      0.014     36.971      0.000       0.489       0.544
C(fiProductClassDesc)[T.Backhoe Loader - Unidentified]                                  0.1815      0.020      8.906      0.000       0.142       0.221
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 0.0 to 2.0 Metric Tons]           -0.5555      0.015    -37.529      0.000      -0.585      -0.527
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 11.0 to 12.0 Metric Tons]          0.5538      0.023     24.359      0.000       0.509       0.598
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons]          0.8082      0.011     74.135      0.000       0.787       0.830
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 14.0 to 16.0 Metric Tons]          0.9729      0.011     84.652      0.000       0.950       0.995
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 150.0 to 300.0 Metric Tons]        0.0650      0.290      0.225      0.822      -0.502       0.633
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 16.0 to 19.0 Metric Tons]          0.9540      0.012     77.308      0.000       0.930       0.978
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 19.0 to 21.0 Metric Tons]          1.0640      0.011     95.279      0.000       1.042       1.086
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 2.0 to 3.0 Metric Tons]           -0.4057      0.012    -33.506      0.000      -0.429      -0.382
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons]          1.1876      0.010    123.901      0.000       1.169       1.206
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 24.0 to 28.0 Metric Tons]          1.1242      0.012     92.191      0.000       1.100       1.148
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 28.0 to 33.0 Metric Tons]          1.2604      0.011    116.081      0.000       1.239       1.282
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 3.0 to 4.0 Metric Tons]           -0.2247      0.010    -21.429      0.000      -0.245      -0.204
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 33.0 to 40.0 Metric Tons]          1.3222      0.010    131.944      0.000       1.303       1.342
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 4.0 to 5.0 Metric Tons]            0.0583      0.014      4.185      0.000       0.031       0.086
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 4.0 to 6.0 Metric Tons]           -0.1102      0.118     -0.934      0.350      -0.342       0.121
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 40.0 to 50.0 Metric Tons]          1.3543      0.012    117.227      0.000       1.332       1.377
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 5.0 to 6.0 Metric Tons]            0.1406      0.014      9.719      0.000       0.112       0.169
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 50.0 to 66.0 Metric Tons]          1.2494      0.022     57.409      0.000       1.207       1.292
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 6.0 to 8.0 Metric Tons]            0.4330      0.014     31.590      0.000       0.406       0.460
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 66.0 to 90.0 Metric Tons]          1.6724      0.032     53.071      0.000       1.611       1.734
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 8.0 to 11.0 Metric Tons]           0.6188      0.018     33.784      0.000       0.583       0.655
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 90.0 to 150.0 Metric Tons]         1.5429      0.080     19.190      0.000       1.385       1.701
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - Unidentified]                      1.0279      0.109      9.397      0.000       0.813       1.242
C(fiProductClassDesc)[T.Motorgrader - 130.0 to 145.0 Horsepower]                        1.8054      0.015    121.288      0.000       1.776       1.835
C(fiProductClassDesc)[T.Motorgrader - 145.0 to 170.0 Horsepower]                        1.7222      0.014    121.689      0.000       1.694       1.750
C(fiProductClassDesc)[T.Motorgrader - 170.0 to 200.0 Horsepower]                        1.8820      0.014    138.698      0.000       1.855       1.909
C(fiProductClassDesc)[T.Motorgrader - 200.0 + Horsepower]                               1.7552      0.024     72.540      0.000       1.708       1.803
C(fiProductClassDesc)[T.Motorgrader - 45.0 to 130.0 Horsepower]                         1.0847      0.017     63.015      0.000       1.051       1.118
C(fiProductClassDesc)[T.Skid Steer Loader - 0.0 to 701.0 Lb Operating Capacity]        -0.7397      0.016    -47.076      0.000      -0.770      -0.709
C(fiProductClassDesc)[T.Skid Steer Loader - 1251.0 to 1351.0 Lb Operating Capacity]    -0.5204      0.012    -44.180      0.000      -0.543      -0.497
C(fiProductClassDesc)[T.Skid Steer Loader - 1351.0 to 1601.0 Lb Operating Capacity]    -0.5235      0.010    -51.020      0.000      -0.544      -0.503
C(fiProductClassDesc)[T.Skid Steer Loader - 1601.0 to 1751.0 Lb Operating Capacity]    -0.4392      0.010    -43.855      0.000      -0.459      -0.420
C(fiProductClassDesc)[T.Skid Steer Loader - 1751.0 to 2201.0 Lb Operating Capacity]    -0.3661      0.010    -38.189      0.000      -0.385      -0.347
C(fiProductClassDesc)[T.Skid Steer Loader - 2201.0 to 2701.0 Lb Operating Capacity]    -0.3121      0.011    -27.655      0.000      -0.334      -0.290
C(fiProductClassDesc)[T.Skid Steer Loader - 2701.0+ Lb Operating Capacity]             -0.2253      0.012    -19.088      0.000      -0.248      -0.202
C(fiProductClassDesc)[T.Skid Steer Loader - 701.0 to 976.0 Lb Operating Capacity]      -0.8752      0.024    -35.794      0.000      -0.923      -0.827
C(fiProductClassDesc)[T.Skid Steer Loader - 976.0 to 1251.0 Lb Operating Capacity]     -0.5309      0.032    -16.649      0.000      -0.593      -0.468
C(fiProductClassDesc)[T.Skid Steer Loader - Unidentified]                              -0.3617      0.018    -19.798      0.000      -0.398      -0.326
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 105.0 to 130.0 Horsepower]          1.0768      0.011     95.687      0.000       1.055       1.099
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 130.0 to 160.0 Horsepower]          1.2714      0.011    119.375      0.000       1.251       1.292
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 160.0 to 190.0 Horsepower]          1.5229      0.011    134.099      0.000       1.501       1.545
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 190.0 to 260.0 Horsepower]          1.4937      0.015     98.687      0.000       1.464       1.523
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 20.0 to 75.0 Horsepower]            0.4865      0.010     50.662      0.000       0.468       0.505
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 260.0 + Horsepower]                 1.9926      0.014    140.501      0.000       1.965       2.020
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 75.0 to 85.0 Horsepower]            0.6045      0.011     53.526      0.000       0.582       0.627
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 85.0 to 105.0 Horsepower]           0.7780      0.009     82.362      0.000       0.759       0.796
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - Unidentified]                       0.6073      0.078      7.766      0.000       0.454       0.761
C(fiProductClassDesc)[T.Wheel Loader - 0.0 to 40.0 Horsepower]                         -0.1531      0.051     -3.011      0.003      -0.253      -0.053
C(fiProductClassDesc)[T.Wheel Loader - 100.0 to 110.0 Horsepower]                       0.8852      0.016     54.047      0.000       0.853       0.917
C(fiProductClassDesc)[T.Wheel Loader - 1000.0 + Horsepower]                            -0.1789      0.289     -0.619      0.536      -0.745       0.388
C(fiProductClassDesc)[T.Wheel Loader - 110.0 to 120.0 Horsepower]                       0.8936      0.024     37.015      0.000       0.846       0.941
C(fiProductClassDesc)[T.Wheel Loader - 120.0 to 135.0 Horsepower]                       1.0298      0.010    102.288      0.000       1.010       1.050
C(fiProductClassDesc)[T.Wheel Loader - 135.0 to 150.0 Horsepower]                       1.1450      0.014     83.762      0.000       1.118       1.172
C(fiProductClassDesc)[T.Wheel Loader - 150.0 to 175.0 Horsepower]                       1.2680      0.010    121.288      0.000       1.247       1.288
C(fiProductClassDesc)[T.Wheel Loader - 175.0 to 200.0 Horsepower]                       1.3721      0.012    115.506      0.000       1.349       1.395
C(fiProductClassDesc)[T.Wheel Loader - 200.0 to 225.0 Horsepower]                       1.5837      0.015    105.361      0.000       1.554       1.613
C(fiProductClassDesc)[T.Wheel Loader - 225.0 to 250.0 Horsepower]                       1.4842      0.019     77.489      0.000       1.447       1.522
C(fiProductClassDesc)[T.Wheel Loader - 250.0 to 275.0 Horsepower]                       1.3431      0.019     68.910      0.000       1.305       1.381
C(fiProductClassDesc)[T.Wheel Loader - 275.0 to 350.0 Horsepower]                       1.5641      0.014    111.908      0.000       1.537       1.591
C(fiProductClassDesc)[T.Wheel Loader - 350.0 to 500.0 Horsepower]                       1.5259      0.021     73.026      0.000       1.485       1.567
C(fiProductClassDesc)[T.Wheel Loader - 40.0 to 60.0 Horsepower]                         0.1257      0.025      5.022      0.000       0.077       0.175
C(fiProductClassDesc)[T.Wheel Loader - 500.0 to 1000.0 Horsepower]                      1.6942      0.049     34.669      0.000       1.598       1.790
C(fiProductClassDesc)[T.Wheel Loader - 60.0 to 80.0 Horsepower]                        -0.0580      0.011     -5.246      0.000      -0.080      -0.036
C(fiProductClassDesc)[T.Wheel Loader - 80.0 to 90.0 Horsepower]                         0.4484      0.038     11.871      0.000       0.374       0.522
C(fiProductClassDesc)[T.Wheel Loader - 90.0 to 100.0 Horsepower]                        0.8060      0.022     37.030      0.000       0.763       0.849
C(fiProductClassDesc)[T.Wheel Loader - Unidentified]                                    0.7918      0.073     10.904      0.000       0.649       0.934
C(sale_year)[T.1990]                                                                   -0.0056      0.033     -0.169      0.866      -0.071       0.060
C(sale_year)[T.1991]                                                                    0.0537      0.031      1.707      0.088      -0.008       0.115
C(sale_year)[T.1992]                                                                   -0.0346      0.032     -1.072      0.284      -0.098       0.029
C(sale_year)[T.1993]                                                                    0.1190      0.031      3.789      0.000       0.057       0.181
C(sale_year)[T.1994]                                                                    0.2860      0.034      8.392      0.000       0.219       0.353
C(sale_year)[T.1995]                                                                    0.2725      0.030      9.023      0.000       0.213       0.332
C(sale_year)[T.1996]                                                                    0.3302      0.028     11.718      0.000       0.275       0.385
C(sale_year)[T.1997]                                                                    0.3615      0.029     12.401      0.000       0.304       0.419
C(sale_year)[T.1998]                                                                    0.2815      0.029      9.594      0.000       0.224       0.339
C(sale_year)[T.1999]                                                                    0.2578      0.027      9.381      0.000       0.204       0.312
C(sale_year)[T.2000]                                                                    0.2851      0.029      9.744      0.000       0.228       0.342
C(sale_year)[T.2004]                                                                    0.3410      0.026     13.360      0.000       0.291       0.391
C(sale_year)[T.2005]                                                                    0.3712      0.025     14.658      0.000       0.322       0.421
C(sale_year)[T.2006]                                                                    0.4125      0.025     16.331      0.000       0.363       0.462
C(sale_year)[T.2007]                                                                    0.4208      0.025     17.140      0.000       0.373       0.469
C(sale_year)[T.2008]                                                                    0.3585      0.024     14.686      0.000       0.311       0.406
C(sale_year)[T.2009]                                                                    0.2438      0.024     10.022      0.000       0.196       0.291
C(sale_year)[T.2010]                                                                    0.3645      0.024     14.968      0.000       0.317       0.412
C(sale_year)[T.2011]                                                                    0.4935      0.024     20.257      0.000       0.446       0.541
C(sale_year)[T.2012]                                                                    0.5810      0.025     23.495      0.000       0.532       0.629
equipment_age                                                                          -0.0984      0.001   -153.038      0.000      -0.100      -0.097
age_squared                                                                             0.0014   2.08e-05     67.286      0.000       0.001       0.001
log_machine_hours                                                                      -0.0165      0.001    -12.038      0.000      -0.019      -0.014
==============================================================================
Omnibus:                     5522.408   Durbin-Watson:                   1.290
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14363.611
Skew:                          -0.475   Prob(JB):                         0.00
Kurtosis:                       5.043   Cond. No.                     5.05e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
class_model = smf.ols(
    """
    log_sale_price ~
    equipment_age +
    age_squared +
    log_machine_hours +
    C(fiProductClassDesc)
    """,
    data=clean_hours_df
).fit()

print(class_model.summary())
print("Adjusted R²:", class_model.rsquared_adj)

                            OLS Regression Results
==============================================================================
Dep. Variable:         log_sale_price   R-squared:                       0.822
Model:                            OLS   Adj. R-squared:                  0.822
Method:                 Least Squares   F-statistic:                     4298.
Date:                Fri, 18 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:29:10   Log-Likelihood:                -15720.
No. Observations:               67884   AIC:                         3.159e+04
Df Residuals:                   67810   BIC:                         3.226e+04
Df Model:                          73
Covariance Type:            nonrobust
=======================================================================================================================================================
                                                                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                              10.2451      0.012    856.391      0.000      10.222      10.269
C(fiProductClassDesc)[T.Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth]        0.4564      0.009     51.500      0.000       0.439       0.474
C(fiProductClassDesc)[T.Backhoe Loader - 15.0 to 16.0 Ft Standard Digging Depth]        0.4956      0.012     42.647      0.000       0.473       0.518
C(fiProductClassDesc)[T.Backhoe Loader - 16.0 + Ft Standard Digging Depth]              0.4996      0.015     33.854      0.000       0.471       0.528
C(fiProductClassDesc)[T.Backhoe Loader - Unidentified]                                  0.1306      0.022      6.070      0.000       0.088       0.173
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 0.0 to 2.0 Metric Tons]           -0.5270      0.016    -33.678      0.000      -0.558      -0.496
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 11.0 to 12.0 Metric Tons]          0.5460      0.024     22.747      0.000       0.499       0.593
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons]          0.7980      0.011     69.394      0.000       0.775       0.821
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 14.0 to 16.0 Metric Tons]          0.9773      0.012     80.489      0.000       0.954       1.001
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 150.0 to 300.0 Metric Tons]       -0.0106      0.305     -0.035      0.972      -0.609       0.588
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 16.0 to 19.0 Metric Tons]          0.9354      0.013     71.849      0.000       0.910       0.961
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 19.0 to 21.0 Metric Tons]          1.0634      0.012     90.252      0.000       1.040       1.086
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 2.0 to 3.0 Metric Tons]           -0.3962      0.013    -30.940      0.000      -0.421      -0.371
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons]          1.1801      0.010    116.660      0.000       1.160       1.200
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 24.0 to 28.0 Metric Tons]          1.1123      0.013     86.352      0.000       1.087       1.138
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 28.0 to 33.0 Metric Tons]          1.2543      0.011    109.337      0.000       1.232       1.277
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 3.0 to 4.0 Metric Tons]           -0.2104      0.011    -18.984      0.000      -0.232      -0.189
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 33.0 to 40.0 Metric Tons]          1.3122      0.011    123.952      0.000       1.291       1.333
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 4.0 to 5.0 Metric Tons]            0.0756      0.015      5.132      0.000       0.047       0.105
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 4.0 to 6.0 Metric Tons]           -0.1756      0.125     -1.407      0.160      -0.420       0.069
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 40.0 to 50.0 Metric Tons]          1.3477      0.012    110.472      0.000       1.324       1.372
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 5.0 to 6.0 Metric Tons]            0.1569      0.015     10.255      0.000       0.127       0.187
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 50.0 to 66.0 Metric Tons]          1.2127      0.023     52.714      0.000       1.168       1.258
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 6.0 to 8.0 Metric Tons]            0.4231      0.014     29.250      0.000       0.395       0.451
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 66.0 to 90.0 Metric Tons]          1.6534      0.033     49.596      0.000       1.588       1.719
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 8.0 to 11.0 Metric Tons]           0.6233      0.019     32.188      0.000       0.585       0.661
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - 90.0 to 150.0 Metric Tons]         1.5172      0.085     17.835      0.000       1.351       1.684
C(fiProductClassDesc)[T.Hydraulic Excavator, Track - Unidentified]                      0.9551      0.116      8.257      0.000       0.728       1.182
C(fiProductClassDesc)[T.Motorgrader - 130.0 to 145.0 Horsepower]                        1.7850      0.016    113.588      0.000       1.754       1.816
C(fiProductClassDesc)[T.Motorgrader - 145.0 to 170.0 Horsepower]                        1.6884      0.015    113.084      0.000       1.659       1.718
C(fiProductClassDesc)[T.Motorgrader - 170.0 to 200.0 Horsepower]                        1.8792      0.014    131.020      0.000       1.851       1.907
C(fiProductClassDesc)[T.Motorgrader - 200.0 + Horsepower]                               1.7461      0.026     68.224      0.000       1.696       1.796
C(fiProductClassDesc)[T.Motorgrader - 45.0 to 130.0 Horsepower]                         1.0720      0.018     58.932      0.000       1.036       1.108
C(fiProductClassDesc)[T.Skid Steer Loader - 0.0 to 701.0 Lb Operating Capacity]        -0.7194      0.017    -43.292      0.000      -0.752      -0.687
C(fiProductClassDesc)[T.Skid Steer Loader - 1251.0 to 1351.0 Lb Operating Capacity]    -0.5160      0.012    -41.524      0.000      -0.540      -0.492
C(fiProductClassDesc)[T.Skid Steer Loader - 1351.0 to 1601.0 Lb Operating Capacity]    -0.5106      0.011    -47.172      0.000      -0.532      -0.489
C(fiProductClassDesc)[T.Skid Steer Loader - 1601.0 to 1751.0 Lb Operating Capacity]    -0.4248      0.011    -40.156      0.000      -0.445      -0.404
C(fiProductClassDesc)[T.Skid Steer Loader - 1751.0 to 2201.0 Lb Operating Capacity]    -0.3463      0.010    -34.195      0.000      -0.366      -0.326
C(fiProductClassDesc)[T.Skid Steer Loader - 2201.0 to 2701.0 Lb Operating Capacity]    -0.2999      0.012    -25.128      0.000      -0.323      -0.277
C(fiProductClassDesc)[T.Skid Steer Loader - 2701.0+ Lb Operating Capacity]             -0.2059      0.012    -16.499      0.000      -0.230      -0.181
C(fiProductClassDesc)[T.Skid Steer Loader - 701.0 to 976.0 Lb Operating Capacity]      -0.8594      0.026    -33.255      0.000      -0.910      -0.809
C(fiProductClassDesc)[T.Skid Steer Loader - 976.0 to 1251.0 Lb Operating Capacity]     -0.5158      0.034    -15.296      0.000      -0.582      -0.450
C(fiProductClassDesc)[T.Skid Steer Loader - Unidentified]                              -0.3426      0.019    -17.740      0.000      -0.380      -0.305
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 105.0 to 130.0 Horsepower]          1.0880      0.012     91.560      0.000       1.065       1.111
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 130.0 to 160.0 Horsepower]          1.2657      0.011    112.615      0.000       1.244       1.288
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 160.0 to 190.0 Horsepower]          1.5065      0.012    125.663      0.000       1.483       1.530
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 190.0 to 260.0 Horsepower]          1.4639      0.016     91.638      0.000       1.433       1.495
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 20.0 to 75.0 Horsepower]            0.4766      0.010     47.169      0.000       0.457       0.496
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 260.0 + Horsepower]                 1.9297      0.015    129.186      0.000       1.900       1.959
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 75.0 to 85.0 Horsepower]            0.6007      0.012     50.429      0.000       0.577       0.624
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - 85.0 to 105.0 Horsepower]           0.7801      0.010     78.325      0.000       0.761       0.800
C(fiProductClassDesc)[T.Track Type Tractor, Dozer - Unidentified]                       0.3946      0.082      4.814      0.000       0.234       0.555
C(fiProductClassDesc)[T.Wheel Loader - 0.0 to 40.0 Horsepower]                         -0.1847      0.054     -3.436      0.001      -0.290      -0.079
C(fiProductClassDesc)[T.Wheel Loader - 100.0 to 110.0 Horsepower]                       0.8322      0.017     48.231      0.000       0.798       0.866
C(fiProductClassDesc)[T.Wheel Loader - 1000.0 + Horsepower]                            -0.2440      0.305     -0.799      0.424      -0.842       0.354
C(fiProductClassDesc)[T.Wheel Loader - 110.0 to 120.0 Horsepower]                       0.8738      0.026     34.232      0.000       0.824       0.924
C(fiProductClassDesc)[T.Wheel Loader - 120.0 to 135.0 Horsepower]                       1.0321      0.011     97.119      0.000       1.011       1.053
C(fiProductClassDesc)[T.Wheel Loader - 135.0 to 150.0 Horsepower]                       1.1309      0.014     78.346      0.000       1.103       1.159
C(fiProductClassDesc)[T.Wheel Loader - 150.0 to 175.0 Horsepower]                       1.2626      0.011    114.519      0.000       1.241       1.284
C(fiProductClassDesc)[T.Wheel Loader - 175.0 to 200.0 Horsepower]                       1.3687      0.013    109.096      0.000       1.344       1.393
C(fiProductClassDesc)[T.Wheel Loader - 200.0 to 225.0 Horsepower]                       1.5813      0.016     99.579      0.000       1.550       1.612
C(fiProductClassDesc)[T.Wheel Loader - 225.0 to 250.0 Horsepower]                       1.4896      0.020     73.551      0.000       1.450       1.529
C(fiProductClassDesc)[T.Wheel Loader - 250.0 to 275.0 Horsepower]                       1.3394      0.021     65.011      0.000       1.299       1.380
C(fiProductClassDesc)[T.Wheel Loader - 275.0 to 350.0 Horsepower]                       1.5559      0.015    105.388      0.000       1.527       1.585
C(fiProductClassDesc)[T.Wheel Loader - 350.0 to 500.0 Horsepower]                       1.4824      0.022     67.172      0.000       1.439       1.526
C(fiProductClassDesc)[T.Wheel Loader - 40.0 to 60.0 Horsepower]                         0.1641      0.026      6.203      0.000       0.112       0.216
C(fiProductClassDesc)[T.Wheel Loader - 500.0 to 1000.0 Horsepower]                      1.6555      0.052     32.028      0.000       1.554       1.757
C(fiProductClassDesc)[T.Wheel Loader - 60.0 to 80.0 Horsepower]                        -0.0757      0.012     -6.473      0.000      -0.099      -0.053
C(fiProductClassDesc)[T.Wheel Loader - 80.0 to 90.0 Horsepower]                         0.4408      0.040     11.039      0.000       0.363       0.519
C(fiProductClassDesc)[T.Wheel Loader - 90.0 to 100.0 Horsepower]                        0.7520      0.023     32.738      0.000       0.707       0.797
C(fiProductClassDesc)[T.Wheel Loader - Unidentified]                                    0.7773      0.077     10.120      0.000       0.627       0.928
equipment_age                                                                          -0.0878      0.001   -134.584      0.000      -0.089      -0.087
age_squared                                                                             0.0012   2.16e-05     55.299      0.000       0.001       0.001
log_machine_hours                                                                      -0.0075      0.001     -5.256      0.000      -0.010      -0.005
==============================================================================
Omnibus:                     4579.072   Durbin-Watson:                   1.258
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9966.377
Skew:                          -0.447   Prob(JB):                         0.00
Kurtosis:                       4.650   Cond. No.                     5.04e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.04e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
Adjusted R²: 0.8221056342125582

In [ ]:
m1 = smf.ols(
    "log_sale_price ~ C(fiProductClassDesc)",
    data=clean_hours_df
).fit()

m2 = smf.ols(
    """
    log_sale_price ~
    C(fiProductClassDesc) +
    C(sale_year)
    """,
    data=clean_hours_df
).fit()

m3 = smf.ols(
    """
    log_sale_price ~
    C(fiProductClassDesc) +
    C(sale_year) +
    equipment_age +
    age_squared
    """,
    data=clean_hours_df
).fit()

m4 = smf.ols(
    """
    log_sale_price ~
    C(fiProductClassDesc) +
    C(sale_year) +
    equipment_age +
    age_squared +
    log_machine_hours
    """,
    data=clean_hours_df
).fit()

print("Class only:           ", m1.rsquared_adj)
print("Class + market year:  ", m2.rsquared_adj)
print("+ equipment age:      ", m3.rsquared_adj)
print("+ operating hours:    ", m4.rsquared_adj)

Class only:            0.6459222824709576
Class + market year:   0.6575600996210602
+ equipment age:       0.8407689449801892
+ operating hours:     0.8411062424895032

## 16. Validate on future data

A random split would let auctions from every year appear in both training and test data, which can make performance look better than a real deployment. Instead, all sales before 2012 form the training set and 2012 is held out as an unseen future period.

The validation model uses `sale_year` as a numeric trend rather than a set of year categories. This is necessary because a categorical model trained only through 2011 would not have learned a coefficient for the unseen 2012 category. The split is repeated in the next cell before fitting; this duplication is harmless and keeps the modeling block self-contained.

In [ ]:
train = clean_hours_df[
    clean_hours_df["sale_year"] < 2012
].copy()

test = clean_hours_df[
    clean_hours_df["sale_year"] == 2012
].copy()

In [ ]:
train = clean_hours_df[
    clean_hours_df["sale_year"] < 2012
].copy()

test = clean_hours_df[
    clean_hours_df["sale_year"] == 2012
].copy()

temporal_model = smf.ols(
    """
    log_sale_price ~
    C(fiProductClassDesc) +
    sale_year +
    equipment_age +
    age_squared +
    log_machine_hours
    """,
    data=train
).fit()

pred = temporal_model.predict(test)

## 17. Evaluate accuracy in both model space and dollars

No single metric tells the full story:

- **Log R²** measures how much variation the model explains on the scale it was trained on.
- **Dollar MAE** reports the average absolute dollar miss after predictions are converted back with `expm1`.
- **Median absolute percentage error** describes the typical proportional miss and is less dominated by a few expensive machines.
- **Median signed percentage error** checks systematic direction. A negative value means the model tends to underpredict.

On the 2012 holdout, the model achieves **0.766 log R²**, about **$10,290 MAE**, and roughly **23.0% median absolute percentage error**. The median signed error is about **−16.2%**, so the uncorrected predictions tend to be conservative. That bias should be surfaced in any calculator that uses the model.

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

print(
    "Test log R²:",
    r2_score(test["log_sale_price"], pred)
)

pred_dollars = np.expm1(pred)

print(
    "Dollar MAE:",
    mean_absolute_error(
        test["SalePrice"],
        pred_dollars
    )
)

Test log R²: 0.7662067856795658
Dollar MAE: 10289.804884505882

In [ ]:
test["predicted_price"] = pred_dollars

test["absolute_pct_error"] = (
    abs(test["SalePrice"] - test["predicted_price"])
    / test["SalePrice"]
)

print(
    "Median absolute % error:",
    test["absolute_pct_error"].median()
)

Median absolute % error: 0.22995773155736776

In [ ]:
test["pct_error"] = (
    test["predicted_price"] - test["SalePrice"]
) / test["SalePrice"]

print(
    "Median signed % error:",
    test["pct_error"].median()
)

Median signed % error: -0.16224009086966168

## 18. Measure reliability by equipment class

Overall metrics can hide weak performance for rare classes. The holdout results are therefore grouped by detailed equipment class to report:

- the number of 2012 test observations,
- the median actual auction price, and
- the median absolute percentage error.

The table is sorted from lowest to highest error. Because a small sample can produce an unstable median, the next view requires at least 20 test observations before a class is described as reliable.

In [ ]:
class_accuracy = (
    test.groupby("fiProductClassDesc")
    .agg(
        count=("SalePrice", "size"),
        median_actual_price=("SalePrice", "median"),
        median_abs_pct_error=("absolute_pct_error", "median")
    )
    .sort_values("median_abs_pct_error")
)

class_accuracy

,count,median_actual_price,median_abs_pct_error
fiProductClassDesc,,,
Wheel Loader - Unidentified,3,13000.0,0.067233
Wheel Loader - 60.0 to 80.0 Horsepower,76,14000.0,0.112098
Backhoe Loader - Unidentified,9,13500.0,0.130369
"Track Type Tractor, Dozer - 20.0 to 75.0 Horsepower",116,19000.0,0.165646
"Track Type Tractor, Dozer - 75.0 to 85.0 Horsepower",70,23000.0,0.169290
...,...,...,...
"Track Type Tractor, Dozer - 190.0 to 260.0 Horsepower",23,53000.0,0.430168
Motorgrader - 45.0 to 130.0 Horsepower,34,21050.0,0.436444
"Hydraulic Excavator, Track - 11.0 to 12.0 Metric Tons",5,27500.0,0.456676
"Hydraulic Excavator, Track - 90.0 to 150.0 Metric Tons",1,60000.0,0.475010
Skid Steer Loader - 0.0 to 701.0 Lb Operating Capacity,18,6000.0,0.508190

In [ ]:
reliable_classes = class_accuracy[
    class_accuracy["count"] >= 20
].copy()

reliable_classes.sort_values("median_abs_pct_error")

,count,median_actual_price,median_abs_pct_error
fiProductClassDesc,,,
Wheel Loader - 60.0 to 80.0 Horsepower,76,14000.0,0.112098
"Track Type Tractor, Dozer - 20.0 to 75.0 Horsepower",116,19000.0,0.165646
"Track Type Tractor, Dozer - 75.0 to 85.0 Horsepower",70,23000.0,0.169290
"Hydraulic Excavator, Track - 3.0 to 4.0 Metric Tons",99,15000.0,0.170072
"Hydraulic Excavator, Track - 0.0 to 2.0 Metric Tons",35,10000.0,0.172312
Skid Steer Loader - 2701.0+ Lb Operating Capacity,47,14000.0,0.181291
"Track Type Tractor, Dozer - 160.0 to 190.0 Horsepower",68,57250.0,0.184143
Backhoe Loader - 16.0 + Ft Standard Digging Depth,40,19000.0,0.186151
"Hydraulic Excavator, Track - 4.0 to 5.0 Metric Tons",30,20250.0,0.186236
Skid Steer Loader - 1751.0 to 2201.0 Lb Operating Capacity,124,12500.0,0.187117
"Hydraulic Excavator, Track - 6.0 to 8.0 Metric Tons",36,25000.0,0.187963
Wheel Loader - 200.0 to 225.0 Horsepower,51,68000.0,0.191936
Wheel Loader - 120.0 to 135.0 Horsepower,106,41000.0,0.192378
"Hydraulic Excavator, Track - 40.0 to 50.0 Metric Tons",84,51000.0,0.194757
"Hydraulic Excavator, Track - 2.0 to 3.0 Metric Tons",69,11500.0,0.195188
Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth,381,25000.0,0.203079
"Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons",63,38000.0,0.205192
Skid Steer Loader - 1601.0 to 1751.0 Lb Operating Capacity,117,10500.0,0.205983
Skid Steer Loader - 1251.0 to 1351.0 Lb Operating Capacity,50,8500.0,0.219279
Skid Steer Loader - 1351.0 to 1601.0 Lb Operating Capacity,82,10000.0,0.219435
"Hydraulic Excavator, Track - 24.0 to 28.0 Metric Tons",64,36000.0,0.219738
Skid Steer Loader - 2201.0 to 2701.0 Lb Operating Capacity,54,14500.0,0.222208
"Hydraulic Excavator, Track - 19.0 to 21.0 Metric Tons",73,44000.0,0.231147
"Hydraulic Excavator, Track - 50.0 to 66.0 Metric Tons",21,37500.0,0.233574
Wheel Loader - 150.0 to 175.0 Horsepower,122,51000.0,0.236401
"Track Type Tractor, Dozer - 85.0 to 105.0 Horsepower",142,33500.0,0.239025
"Hydraulic Excavator, Track - 28.0 to 33.0 Metric Tons",92,48000.0,0.241455
Motorgrader - 130.0 to 145.0 Horsepower,34,81250.0,0.246862
Wheel Loader - 175.0 to 200.0 Horsepower,82,56500.0,0.251811
Wheel Loader - 250.0 to 275.0 Horsepower,20,46000.0,0.261046
"Hydraulic Excavator, Track - 14.0 to 16.0 Metric Tons",69,39100.0,0.261164
Wheel Loader - 135.0 to 150.0 Horsepower,30,46250.0,0.263686
"Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons",135,47500.0,0.274139
"Hydraulic Excavator, Track - 5.0 to 6.0 Metric Tons",31,23000.0,0.276775
Backhoe Loader - 15.0 to 16.0 Ft Standard Digging Depth,105,20000.0,0.280040
"Track Type Tractor, Dozer - 105.0 to 130.0 Horsepower",53,47500.0,0.283854
Backhoe Loader - 0.0 to 14.0 Ft Standard Digging Depth,78,21000.0,0.292300
Wheel Loader - 100.0 to 110.0 Horsepower,21,23000.0,0.293521
"Track Type Tractor, Dozer - 130.0 to 160.0 Horsepower",123,50000.0,0.294086
"Hydraulic Excavator, Track - 33.0 to 40.0 Metric Tons",100,62500.0,0.294315
"Hydraulic Excavator, Track - 16.0 to 19.0 Metric Tons",32,57000.0,0.306509
Motorgrader - 170.0 to 200.0 Horsepower,51,101000.0,0.312754
Wheel Loader - 275.0 to 350.0 Horsepower,69,63000.0,0.316881
Wheel Loader - 225.0 to 250.0 Horsepower,35,77500.0,0.329807
"Track Type Tractor, Dozer - 260.0 + Horsepower",53,70000.0,0.359806
Motorgrader - 145.0 to 170.0 Horsepower,48,70000.0,0.399334
"Track Type Tractor, Dozer - 190.0 to 260.0 Horsepower",23,53000.0,0.430168
Motorgrader - 45.0 to 130.0 Horsepower,34,21050.0,0.436444

### Create user-facing confidence labels

The confidence function combines sample size and observed holdout error:

- **High:** at least 50 test sales and median error no greater than 25%.
- **Moderate:** at least 20 test sales and median error no greater than 40%.
- **Low:** all other combinations.

These are pragmatic communication thresholds, not formal prediction intervals. They help a calculator warn users when a point estimate is based on sparse or historically inconsistent data. Across classes with at least 20 observations, the overall median absolute percentage error remains about **22.9%**.

In [ ]:
def confidence_level(row):
    if row["count"] >= 50 and row["median_abs_pct_error"] <= 0.25:
        return "High"
    elif row["count"] >= 20 and row["median_abs_pct_error"] <= 0.40:
        return "Moderate"
    else:
        return "Low"

class_accuracy["confidence"] = class_accuracy.apply(
    confidence_level,
    axis=1
)

In [ ]:
reliable_test = test[
    test["fiProductClassDesc"].isin(
        reliable_classes.index
    )
]

print(
    "Reliable-class median APE:",
    reliable_test["absolute_pct_error"].median()
)

Reliable-class median APE: 0.2290143701367423

## 19. Refit the deployment model on all cleaned data

After model design and validation are complete, the same formula is fit once more using the full cleaned dataset, including 2012. This is intentional: the holdout remains untouched while choices are evaluated, then its information is recovered for the artifact that will power the calculator.

The deployed formula uses detailed class, numeric sale year, curved age, and log meter hours to predict log sale price. A future application must recreate these transformations exactly and should reject equipment classes that were not present during training.

In [ ]:
calculator_model = smf.ols(
    """
    log_sale_price ~
    C(fiProductClassDesc) +
    sale_year +
    equipment_age +
    age_squared +
    log_machine_hours
    """,
    data=clean_hours_df
).fit()

## 20. Export the model and allowed classes

The remaining cells create the files needed by a downstream application:

1. Save the fitted statsmodels result as a pickle.
2. Export the sorted class list for a valid dropdown menu.
3. Test a compressed `joblib` alternative and measure its file size.
4. Re-save the statsmodels model with `remove_data=True` to reduce unnecessary training-data payload.

The exported model is still approximately **48 MiB**, so repository or hosting file-size limits should be checked. Serialization also ties the artifact to compatible Python and statsmodels versions—the environment record at the top of the notebook is therefore part of the deployment documentation.

In [ ]:
from pathlib import Path

Path("models").mkdir(exist_ok=True)

calculator_model.save(
    "models/residual_value_model.pkl"
)

In [ ]:
classes = sorted(
    clean_hours_df["fiProductClassDesc"]
    .dropna()
    .unique()
)

pd.Series(classes).to_csv(
    "models/equipment_classes.csv",
    index=False,
    header=False
)

In [ ]:
import joblib
from pathlib import Path

Path("models").mkdir(exist_ok=True)

joblib.dump(
    calculator_model,
    "models/residual_value_model.joblib",
    compress=3
)

['models/residual_value_model.joblib']

In [ ]:
from pathlib import Path

size_mb = Path("models/residual_value_model.joblib").stat().st_size / (1024 ** 2)
print(f"{size_mb:.1f} MB")

44.4 MB

In [ ]:
calculator_model.save(
    "models/residual_value_model.pkl",
    remove_data=True
)

In [ ]:
from pathlib import Path

model_path = Path("models/residual_value_model.pkl")

size_bytes = model_path.stat().st_size
size_mib = size_bytes / (1024 ** 2)

print(f"Model size: {size_mib:.2f} MiB")

Model size: 47.91 MiB

## Interpretation and limitations

The final model is useful as an **estimated historical auction value**, but it is not a complete ownership decision by itself.

- The data end in 2012, so dollar predictions are not automatically adjusted to today's market or inflation.
- Rows with missing or zero meter readings are excluded; predictions may not generalize to machines without reliable hours.
- Condition, geography, manufacturer, model, attachments, and auction-specific factors are not included in the final formula.
- The observed 2012 bias suggests that the raw point estimates tend to be low.
- Confidence labels summarize historical test performance; they are not statistical prediction intervals or guarantees.

For a rent-versus-own calculator, the residual-value estimate should be shown with a range and combined with acquisition price, expected utilization, rental rates, transportation, maintenance, financing, downtime, and the planned ownership horizon. A strong next modeling step would be to add inflation/current-market calibration and generate class-specific prediction intervals.